#!/usr/bin/env python3
"""Compile the web app into the offline bundle the iOS app ships.

Reads static/index.html and vocab/*.csv and writes ios/MyConLearn/www/:

    index.html   generated — the shared UI, pointed at vendored/offline assets
    vocab.js     generated — every CSV row, compiled in

The rest of www/ (local-api.js, mobile.css, vendor/) is checked in by hand.

Run this after editing any CSV, then rebuild in Xcode:

    poetry run python scripts/build_ios_www.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.vocab_loader import get_available_topics, load_csv_file  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SOURCE_HTML = PROJECT_ROOT / "static" / "index.html"
WWW_DIR = PROJECT_ROOT / "ios" / "MyConLearn" / "www"

REQUIRED_ASSETS = [
    "local-api.js",
    "mobile.css",
    "vendor/vue.global.prod.js",
    "vendor/tailwind.js",
]

# Each entry is (description, exact source text, replacement). A substitution
# that no longer matches aborts the build rather than silently producing a
# bundle that falls back to the network or misses the offline shim.
SUBSTITUTIONS = [
    (
        "viewport meta",
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0, '
        'viewport-fit=cover, maximum-scale=1.0, user-scalable=no">\n'
        '    <meta name="apple-mobile-web-app-capable" content="yes">\n'
        '    <meta name="apple-mobile-web-app-status-bar-style" content="default">',
    ),
    (
        "Vue CDN tag",
        '<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>',
        '<script src="vendor/vue.global.prod.js"></script>',
    ),
    (
        "Tailwind CDN tag",
        '<script src="https://cdn.tailwindcss.com"></script>',
        '<script src="vendor/tailwind.js"></script>\n'
        '    <link rel="stylesheet" href="mobile.css">\n'
        '    <script src="vocab.js"></script>\n'
        '    <script src="local-api.js"></script>',
    ),
]

BANNER = "GENERATED by scripts/build_ios_www.py — do not edit; edit the source and rebuild."


def collect_vocab() -> tuple[list[dict], list[dict]]:
    """Load every CSV the way load_topic_into_db() would, in the same order.

    Returns (topics, cards). Cards keep first-wins deduplication on
    (vietnamese, english) so the bundle matches what a server sync produces.
    """
    topics: list[dict] = []
    cards: list[dict] = []
    seen: set[tuple[str, str]] = set()

    for topic in get_available_topics():
        path = Path(topic["path"])
        # Same fallback as load_topic_into_db(): "common_verbs.csv" -> "common verbs".
        default_category = path.stem.replace("_", " ").replace("-", " ")

        count = 0
        for row in load_csv_file(path):
            key = (row["vietnamese"], row["english"])
            if key in seen:
                continue
            seen.add(key)
            cards.append(
                {
                    "v": row["vietnamese"],
                    "e": row["english"],
                    "c": row["category"] or default_category,
                    "d": row["difficulty_level"],
                }
            )
            count += 1

        topics.append({"name": topic["name"], "filename": topic["filename"], "count": count})

    return topics, cards


def render_vocab_js(topics: list[dict], cards: list[dict]) -> str:
    payload = {"topics": topics, "cards": cards}
    # ensure_ascii keeps the file pure ASCII, so the diacritics survive
    # regardless of how the WebView guesses the script's encoding.
    body = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    return f"/* {BANNER} */\nwindow.MYCON_VOCAB = {body};\n"


def render_index_html() -> str:
    """Rewrite the shared UI to run against the offline bundle."""
    html = SOURCE_HTML.read_text(encoding="utf-8")

    for description, old, new in SUBSTITUTIONS:
        if old not in html:
            raise SystemExit(
                f"error: could not find the {description} in {SOURCE_HTML.relative_to(PROJECT_ROOT)}.\n"
                f"       static/index.html changed; update SUBSTITUTIONS in {Path(__file__).name}.\n"
                f"       looking for: {old}"
            )
        html = html.replace(old, new, 1)

    return html.replace("<head>", f"<head>\n    <!-- {BANNER} -->", 1)


def write_vocab_js(topics: list[dict], cards: list[dict]) -> Path:
    target = WWW_DIR / "vocab.js"
    target.write_text(render_vocab_js(topics, cards), encoding="utf-8")
    return target


def write_index_html() -> Path:
    target = WWW_DIR / "index.html"
    target.write_text(render_index_html(), encoding="utf-8")
    return target


def check_assets() -> None:
    missing = [name for name in REQUIRED_ASSETS if not (WWW_DIR / name).exists()]
    if missing:
        raise SystemExit(
            "error: missing checked-in assets under ios/MyConLearn/www/:\n"
            + "\n".join(f"       {name}" for name in missing)
        )


def main() -> None:
    if not SOURCE_HTML.exists():
        raise SystemExit(f"error: {SOURCE_HTML} not found")

    WWW_DIR.mkdir(parents=True, exist_ok=True)
    check_assets()

    topics, cards = collect_vocab()
    if not cards:
        raise SystemExit("error: no vocabulary found in vocab/ — nothing to bundle")

    vocab_js = write_vocab_js(topics, cards)
    index_html = write_index_html()

    print(f"Bundled {len(cards)} cards from {len(topics)} CSV files:")
    for topic in topics:
        print(f"  {topic['count']:>4}  {topic['filename']}")
    print()
    for path in (index_html, vocab_js):
        size = path.stat().st_size
        print(f"  wrote {path.relative_to(PROJECT_ROOT)} ({size:,} bytes)")
    print("\nNext: open ios/MyConLearn.xcodeproj in Xcode and press Run.")


if __name__ == "__main__":
    main()
